CREATE TABLE IF NOT EXISTS user_devices (
    id SERIAL PRIMARY KEY,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fcm_token TEXT,
    user_id VARCHAR(20) REFERENCES users(id)
);
