CREATE TABLE IF NOT EXISTS Audit_Trail(
    id SERIAL PRIMARY KEY,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id VARCHAR(20) REFERENCES users(id) NOT NULL,
    action TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS System_Log(
    id SERIAL PRIMARY KEY,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id VARCHAR(20) REFERENCES users(id) NOT NULL,
    error TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS Notification(
    id SERIAL PRIMARY KEY,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id VARCHAR(20) REFERENCES users(id) NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Mqtt_Topic(
    id SERIAL PRIMARY KEY,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    topic_string TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Mqtt_Log(
    id SERIAL PRIMARY KEY,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mqtt_topic_id INTEGER REFERENCES Mqtt_Topic(id) NOT NULL,
    message TEXT NOT NULL
);
